window.KIDS_FAQ={
  categories:[
    ['trial','無料体験・入会'],['age','年齢・クラス'],['price','料金・ファミリー割引'],['schedule','スケジュール・通い方'],['practice','練習内容'],['safety','安全・ケガ'],['development','子供の性格・発達'],['coaching','指導者・指導方針'],['gear','道着・持ち物'],['belt','帯・昇級・大会'],['parents','保護者・付き添い'],['access','施設・アクセス'],['language','日本語・English'],['health','衛生・体調管理'],['privacy','写真・SNS・プライバシー'],['other','その他・スタッフに相談']
  ],
  synonyms:{料金:['料金','月謝','値段','費用','いくら','会費'],年齢:['年齢','何歳','4歳','幼児','小学生','中学生'],体験:['体験','無料','見学','お試し','初めて'],安全:['安全','危険','怪我','ケガ','痛い','怖い'],服装:['服装','道着','ギ','ラッシュガード','Tシャツ','持ち物'],家族:['家族','親子','兄弟','姉妹','ファミリー','割引'],言語:['英語','English','日本語','外国人','インターナショナル'],発達:['ADHD','ASD','発達','グレーゾーン','集中','落ち着き'],大会:['大会','試合','コンペ','competition'],退会:['退会','休会','辞める','解約']},
  items:[
    {id:'trial-001',category:'trial',question:{ja:'無料体験はできますか？',en:'Can we try a class for free?'},answer:{ja:'見学・無料体験ができます。無料体験はお一人様1回です。',en:'Visits and one free trial are available per child.'},keywords:['無料体験','体験','見学','お試し','初めて'],status:'A_WEB_CONFIRMED',source:'official_web',updatedAt:'2026-09-22',cta:'trial'},
    {id:'trial-002',category:'trial',question:{ja:'体験当日はいつ来ればいいですか？',en:'When should we arrive for a trial?'},answer:{ja:'クラス開始10分前を目安にご来館ください。',en:'Please arrive around 10 minutes before class starts.'},keywords:['10分前','来館','開始','体験当日'],status:'A_WEB_CONFIRMED',source:'official_web',updatedAt:'2026-09-22',cta:'trial'},
    {id:'age-001',category:'age',question:{ja:'何歳から参加できますか？',en:'What ages can join?'},answer:{ja:'キッズ柔術は4歳から中学生までを対象としています。4〜6歳、7〜13歳、曜日によって4〜13歳の合同クラスがあります。',en:'Kids Jiu-Jitsu is for ages 4 through junior high school.'},keywords:['年齢','何歳','4歳','中学生','幼児','小学生'],status:'A_WEB_CONFIRMED',source:'official_web',updatedAt:'2026-09-22',cta:'schedule'},
    {id:'age-002',category:'age',question:{ja:'4歳未満でも参加できますか？',en:'Can children under four join?'},answer:{ja:'キッズ柔術は4歳からを対象としています。4歳未満のお子様についてはスタッフへご相談ください。',en:'Kids Jiu-Jitsu starts at age four. Please ask staff about younger children.'},keywords:['4歳未満','3歳','年少','幼児'],status:'B_CONFIRM_REQUIRED',source:null,updatedAt:'2026-09-22',cta:'contact'},
    {id:'price-001',category:'price',question:{ja:'月謝はいくらですか？',en:'What is the monthly fee?'},answer:{ja:'キッズ柔術＋体操は月額9,000円、キッズ体操のみは月額5,000円です。入会金は10,000円です。税込・税別の表記はお申し込み前にご確認ください。',en:'Kids Jiu-Jitsu + gymnastics is ¥9,000/month; gymnastics only is ¥5,000/month. Enrollment is ¥10,000.'},keywords:['料金','月謝','値段','費用','いくら','会費','9000','5000','10000'],status:'A_WEB_CONFIRMED',source:'official_web',updatedAt:'2026-09-22',cta:'trial'},
    {id:'price-002',category:'price',question:{ja:'ファミリー割引はありますか？',en:'Is there a family discount?'},answer:{ja:'ファミリー割引の詳細は現在確認中です。スタッフへご相談ください。',en:'Family discount details are being confirmed. Please ask staff.'},keywords:['家族','兄弟','姉妹','親子','ファミリー','割引'],status:'B_CONFIRM_REQUIRED',source:null,updatedAt:'2026-09-22',cta:'contact'},
    {id:'schedule-001',category:'schedule',question:{ja:'週何回通えますか？',en:'How often can my child attend?'},answer:{ja:'キッズ柔術は月額9,000円で通い放題として案内されています。最新の曜日・時間はスケジュールをご確認ください。',en:'Kids Jiu-Jitsu is listed as unlimited attendance for ¥9,000/month. Check the schedule for current times.'},keywords:['週何回','通い放題','毎日','スケジュール','曜日'],status:'A_WEB_CONFIRMED',source:'official_web',updatedAt:'2026-09-22',cta:'schedule'},
    {id:'schedule-002',category:'schedule',question:{ja:'祝日もクラスはありますか？',en:'Are classes held on holidays?'},answer:{ja:'祝日の扱いは掲載情報に差異があるため、最新の予定をスタッフへご確認ください。',en:'Please confirm the latest holiday schedule with staff.'},keywords:['祝日','休み','営業','休館'],status:'B_CONFIRM_REQUIRED',source:null,updatedAt:'2026-09-22',cta:'contact'},
    {id:'practice-001',category:'practice',question:{ja:'キッズ体操では何をしますか？',en:'What happens in kids gymnastics?'},answer:{ja:'前転・後転などのマット運動、柔軟、マットやボールを使った遊びを取り入れた練習を行います。挨拶・礼儀と、柔術につながる身体の使い方も大切にしています。',en:'The class includes mat movement, flexibility, and playful drills with mats and balls.'},keywords:['体操','前転','後転','柔軟','ボール','運動'],status:'A_WEB_CONFIRMED',source:'official_web',updatedAt:'2026-09-22',cta:'trial'},
    {id:'safety-001',category:'safety',question:{ja:'初心者でも大丈夫ですか？',en:'Is it okay for beginners?'},answer:{ja:'初心者でも参加できます。お子様一人ひとりのレベルに合わせて指導する案内があります。',en:'Beginners are welcome and instruction is matched to each child’s level.'},keywords:['初心者','初めて','運動苦手','怖い','安全'],status:'A_WEB_CONFIRMED',source:'official_web',updatedAt:'2026-09-22',cta:'trial'},
    {id:'safety-002',category:'safety',question:{ja:'スポーツ保険には加入しますか？',en:'Is sports insurance included?'},answer:{ja:'補償内容を含め、現在確認中です。詳しくはスタッフへお問い合わせください。',en:'Coverage details are being confirmed. Please ask staff.'},keywords:['保険','スポーツ保険','怪我','ケガ','補償'],status:'B_CONFIRM_REQUIRED',source:null,updatedAt:'2026-09-22',cta:'contact'},
    {id:'development-001',category:'development',question:{ja:'人見知りや発達面が気になる場合も相談できますか？',en:'Can we discuss developmental or social concerns?'},answer:{ja:'お子様によって必要なサポートが異なるため、体験前にスタッフへご相談ください。',en:'Each child may need different support, so please talk with staff before a trial.'},keywords:['ADHD','ASD','発達','グレーゾーン','人見知り','集中','落ち着き'],status:'B_CONFIRM_REQUIRED',source:null,updatedAt:'2026-09-22',cta:'contact'},
    {id:'coaching-001',category:'coaching',question:{ja:'黒帯の先生が教えますか？',en:'Do black belt instructors teach?'},answer:{ja:'キッズページには黒帯インストラクターが指導する旨が掲載されています。',en:'The kids page states that black belt instructors teach the class.'},keywords:['黒帯','先生','コーチ','指導者','インストラクター'],status:'A_WEB_CONFIRMED',source:'official_web',updatedAt:'2026-09-22',cta:'trial'},
    {id:'gear-001',category:'gear',question:{ja:'道着を持っていなくても体験できますか？',en:'Can we try without a gi?'},answer:{ja:'体験用の柔術着は無料でレンタルできます。',en:'A trial gi can be rented free of charge.'},keywords:['道着','ギ','レンタル','服装','持ち物'],status:'A_WEB_CONFIRMED',source:'official_web',updatedAt:'2026-09-22',cta:'trial'},
    {id:'gear-002',category:'gear',question:{ja:'体験には何を持っていけばいいですか？',en:'What should we bring to a trial?'},answer:{ja:'柔術クラスはラッシュガードをご持参ください。その他のクラスは動きやすい服装で参加できます。追加の持ち物はスタッフへご確認ください。',en:'Bring a rash guard for Jiu-Jitsu. Wear comfortable clothes for other classes.'},keywords:['服装','道着','ラッシュガード','Tシャツ','持ち物'],status:'A_WEB_CONFIRMED',source:'official_web',updatedAt:'2026-09-22',cta:'trial'},
    {id:'belt-001',category:'belt',question:{ja:'帯の昇級や大会参加について知りたいです',en:'How do promotions and competitions work?'},answer:{ja:'帯・昇級・大会参加の運用はスタッフへご相談ください。',en:'Please ask staff about promotions and competition participation.'},keywords:['帯','昇級','ストライプ','大会','試合','コンペ'],status:'B_CONFIRM_REQUIRED',source:null,updatedAt:'2026-09-22',cta:'contact'},
    {id:'parents-001',category:'parents',question:{ja:'保護者の付き添いは必要ですか？',en:'Must a guardian stay during class?'},answer:{ja:'付き添いや見学中の対応はスタッフへご相談ください。',en:'Please ask staff about guardian attendance and visits.'},keywords:['保護者','付き添い','送迎','見学','待合'],status:'B_CONFIRM_REQUIRED',source:null,updatedAt:'2026-09-22',cta:'contact'},
    {id:'access-001',category:'access',question:{ja:'駐車場はありますか？',en:'Is parking available?'},answer:{ja:'屋根付き駐車場があります。所在地は沖縄県中頭郡北谷町北谷2丁目14-4 ワイズコーストテラスアラハ2Fです。',en:'Covered parking is available. The location is Wise Coast Terrace Araha 2F, 2-14-4 Chatan, Okinawa.'},keywords:['駐車場','アクセス','住所','北谷','車'],status:'A_WEB_CONFIRMED',source:'official_web',updatedAt:'2026-09-22',cta:'schedule'},
    {id:'language-001',category:'language',question:{ja:'日本語・英語での対応について知りたいです',en:'What language support is available?'},answer:{ja:'対応言語やクラス内でのサポートはスタッフへご相談ください。',en:'Please ask staff about language support in class.'},keywords:['英語','English','日本語','外国人','インターナショナル'],status:'B_CONFIRM_REQUIRED',source:null,updatedAt:'2026-09-22',cta:'contact'},
    {id:'health-001',category:'health',question:{ja:'体調不良やアレルギーがある場合はどうすればいいですか？',en:'What if my child is unwell or has allergies?'},answer:{ja:'お子様の体調や必要な配慮について、体験前にスタッフへご相談ください。',en:'Please talk with staff before a trial about health needs.'},keywords:['アレルギー','アトピー','発熱','体調','感染症','爪'],status:'B_CONFIRM_REQUIRED',source:null,updatedAt:'2026-09-22',cta:'contact'},
    {id:'privacy-001',category:'privacy',question:{ja:'写真やSNSへの掲載について知りたいです',en:'What is the photo and social media policy?'},answer:{ja:'撮影やSNS掲載に関する方針はスタッフへご相談ください。',en:'Please ask staff about photography and social media policies.'},keywords:['写真','SNS','撮影','プライバシー','掲載'],status:'B_CONFIRM_REQUIRED',source:null,updatedAt:'2026-09-22',cta:'contact'},
    {id:'campaign-001',category:'trial',question:{ja:'入会キャンペーンはありますか？',en:'Is there an enrollment campaign?'},answer:{ja:'無料体験後、当日入会で道着と帯をプレゼントするキャンペーンを案内しています。適用条件・終了時期はお申し込み前にご確認ください。',en:'A gi and belt campaign is listed for same-day enrollment after a free trial. Confirm terms before applying.'},keywords:['キャンペーン','道着','帯','プレゼント','入会'],status:'A_WEB_CONFIRMED',source:'official_web',updatedAt:'2026-09-22',cta:'trial'}
  ]
};
